// swift-tools-version: 5.8
// The swift-tools-version declares the minimum version of Swift required to build this package.
//
// An AATKit adapter package: one ad network or CMP, its SDK, and nothing else.
// Generated by BuildScripts/SPM_scripts/BinariesGenerator in the AATKit
// repository, from the routing table in PackageManifest.swift.
//
// The dependency lists and the binary target list are rewritten on every
// release. Keep every Mark comment exactly as it is, keep the binary targets
// last in the file, and never repeat a Mark comment's text elsewhere in the
// file — the generator locates them by string match.

import PackageDescription

let package = Package(
    name: "AATKit-MolocoBidding",
    platforms: [.iOS(.v13)],
    products: [
        .library(name: "AATKit-MolocoBidding", targets: ["AATKit-MolocoBidding"]),
    ],
    dependencies: [
        // Mark: Dependencies Begin
        .package(url: "https://github.com/AddApptr/AATKit.git", exact: "3.18.0-beta3"),
        .package(url: "https://github.com/AddApptr/AATKit-GraviteRTB.git", exact: "3.18.0-beta3"),
        // Mark: Dependencies End
    ],
    // Mark: Targets
    targets: [
        .target(name: "AATKit-MolocoBidding",
                dependencies: [
                    // Mark: Target Dependencies Begin
                    .product(name: "AATKit-Core", package: "AATKit"),
                    .product(name: "AATKit-GraviteRTB", package: "AATKit-GraviteRTB"),
                    "AATMolocoBiddingDSPAdapter",
                    "AATMolocoSDK",
                    // Mark: Target Dependencies End
                ],
                path: "./Sources/AATKit-MolocoBidding"),

        // Mark: Binary Targets
        .binaryTarget(
            name: "AATMolocoBiddingDSPAdapter",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta3/AATMolocoBiddingDSPAdapter.zip",
            checksum: "de73456231c168469c547b6dbae05fac172dd19de8735f8f06c2ace9dc87269c"
        ),
        .binaryTarget(
            name: "AATMolocoSDK",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0-beta3/MolocoSDK.zip",
            checksum: "0faca2b2bafce7ac5690fd107dc090c0fca38e661fcbe6a2d44e584c5958a4a5"
        ),
    ]
)
