// swift-tools-version: 5.8
// The swift-tools-version declares the minimum version of Swift required to build this package.
//
// An AATKit adapter package: one ad network or CMP, its SDK, and nothing else.
// Generated by BuildScripts/SPM_scripts/BinariesGenerator in the AATKit
// repository, from the routing table in PackageManifest.swift.
//
// The dependency lists and the binary target list are rewritten on every
// release. Keep every Mark comment exactly as it is, keep the binary targets
// last in the file, and never repeat a Mark comment's text elsewhere in the
// file — the generator locates them by string match.

import PackageDescription

let package = Package(
    name: "AATKit-MolocoBidding",
    platforms: [.iOS(.v13)],
    products: [
        .library(name: "AATKit-MolocoBidding", targets: ["AATKit-MolocoBidding"]),
    ],
    dependencies: [
        // Mark: Dependencies Begin
        .package(url: "https://github.com/AddApptr/AATKit.git", exact: "3.18.0"),
        .package(url: "https://github.com/AddApptr/AATKit-GraviteRTB.git", exact: "3.18.0"),
        // Mark: Dependencies End
    ],
    // Mark: Targets
    targets: [
        .target(name: "AATKit-MolocoBidding",
                dependencies: [
                    // Mark: Target Dependencies Begin
                    .product(name: "AATKit-Core", package: "AATKit"),
                    .product(name: "AATKit-GraviteRTB", package: "AATKit-GraviteRTB"),
                    "AATMolocoBiddingDSPAdapter",
                    "AATMolocoSDK",
                    // Mark: Target Dependencies End
                ],
                path: "./Sources/AATKit-MolocoBidding"),

        // Mark: Binary Targets
        .binaryTarget(
            name: "AATMolocoBiddingDSPAdapter",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0/AATMolocoBiddingDSPAdapter.zip",
            checksum: "b8586e583198b5c71542bedbee3275834e4c8d5ddb1f081434903130b9c982a3"
        ),
        .binaryTarget(
            name: "AATMolocoSDK",
            url: "https://gravite-sdk-releases.s3.eu-central-1.amazonaws.com/aatkit/ios/spm/3.18.0/MolocoSDK.zip",
            checksum: "7fc354677099ab488485d0c54cdf4b50aa5958a304b8644f09420b3caa9b8773"
        ),
    ]
)
